### ISSUE TITLE
how to fix this sir?

### ISSUE THREAD

**Issue by one9three** [GNUWorldChannel/GNUWorld2020#1]
![B79FF713-3A3F-4A7B-9B8A-5F9333855AF6](https://user-images.githubusercontent.com/66469410/86242201-e5bd3800-bbd6-11ea-928e-b892e81f26de.jpeg)
hi sir, how to fix this error for admin * login?

**Comment by ARI3LUnet** [comment]
Take in consideration what i replied in your other post. Remember, current cservice-web official realease is deprecated, and we
didn´t include that part into our guide. You need to poke official undernet coders about this.
